[project]
name = "wait-bucket-ready"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kubernetes>=31.0.0",
    "python-dotenv>=1.0.1",
]
