name: Bump Chart Version

on: 
    workflow_call:
        inputs:
            chart-path:
                required: true
                type: string

  
jobs:
    version:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - uses: actions/checkout@v4
        - name: Conventional Changelog Action
          uses: TriPSs/conventional-changelog-action@v5
          with:
            github-token: ${{ secrets.github_token }}
            git-message: 'chore(release): {version}'
            version-file: '${{ inputs.chart-path }}/Chart.yaml'
            skip-on-empty: 'false'
            tag-prefix: ''
            create-summary: true
            skip-git-pull: true