name: Bump Chart Version

on: 
    workflow_call:
        inputs:
            chart-path:
                required: true
                type: string

  
jobs:
    version:
        runs-on: ubuntu-latest
        permissions:
            contents: write           # 'write' access to repository contents
            pull-requests: write      # 'write' access to pull requests
        steps:
        - name: Pull Repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Fetch main Branch
          run: |
            git config --global user.email "conventional.changelog.action@github.com"
            git config --global user.name "Conventional Changelog Action"
            git fetch origin main:main
        - name: Get Previous Version and Hash
          id: get_version_hash
          run: |
            VERSION=$(git cherry -v main HEAD | grep "chore(release): chart:" | tail -n 1 | awk '{print $5}')
            COMMIT_HASH=$(git cherry -v main HEAD | grep "chore(release): chart:" | tail -n 1 | awk '{print $2}')
            echo "::set-output name=version::$VERSION"
            echo "::set-output name=hash::$COMMIT_HASH"
        - name: Remove Previous Version and Hash
          if: ${{ steps.get_version_hash.outputs.hash != '' }}
          run: |
            VERSION=${{ steps.get_version_hash.outputs.version }}
            COMMIT_HASH=${{ steps.get_version_hash.outputs.hash }}
            git tag -d $VERSION
            git rebase --onto $COMMIT_HASH^ $COMMIT_HASH

        - name: Conventional Changelog Action
          uses: TriPSs/conventional-changelog-action@v5
          with:
            github-token: ${{ secrets.github_token }}
            git-message: 'chore(release): chart: {version}'
            version-file: '${{ inputs.chart-path }}/Chart.yaml'
            output-file: '${{ inputs.chart-path }}/CHANGELOG.md'
            skip-on-empty: 'false'
            tag-prefix: ''
            create-summary: true
            skip-git-pull: true
            git-push: false
        - name: Push Changes
          run: |
            git push --force
        