name: Bump Chart Version

on: 
    workflow_call:
        inputs:
            chart-path:
                required: true
                type: string

  
jobs:
    version:
        runs-on: ubuntu-latest
        permissions:
            contents: write           # 'write' access to repository contents
            pull-requests: write      # 'write' access to pull requests
        steps:
        - name: Pull Repository
          uses: actions/checkout@v4
          with:
            ref: ${{ github.head_ref }}
            fetch-depth: 0
        - name: Conventional Changelog Action
          uses: TriPSs/conventional-changelog-action@v5
          with:
            github-token: ${{ secrets.github_token }}
            git-message: 'chore(release): chart: {version}'
            version-file: '${{ inputs.chart-path }}/Chart.yaml'
            input-file: '${{ inputs.chart-path }}/CHANGELOG.md'
            skip-on-empty: 'false'
            tag-prefix: ''
            create-summary: true
            skip-git-pull: true
            git-push: false
        - name: Push Changes
          uses: ad-m/github-push-action@master
          with:
            branch: ${{ github.head_ref }}
        