name: Pull Request to Main
on:
    pull_request:
        types: [opened, reopened, synchronize]
        branches: main

  
jobs:
    filter-changes:
        runs-on: ubuntu-latest
        outputs:
            private-vectordb-chart-changed: ${{ steps.changes.outputs.private-vectordb-chart }}
            seed-data-container-changed: ${{ steps.changes.outputs.seed-data-container }}
            search-vectors-container-changed: ${{ steps.changes.outputs.search-vectors-container }}
            wait-bucket-ready-container-changed: ${{ steps.changes.outputs.wait-bucket-ready-container }}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: changes
              with:
                filters: |
                    private-vectordb-chart:
                        - 'charts/private-vectordb/**'
                    seed-data-container:
                        - 'containers/seed-data/**'
                    search-vectors-container:
                        - 'containers/search-vectors/**'
                    wait-bucket-ready-container:
                        - 'containers/wait-bucket-ready/**'

    # Chart jobs
    
    
    # Populate data container jobs
    build-seed-data-container:
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write
        needs: [filter-changes]
        if: ${{ needs.filter-changes.outputs.seed-data-container-changed == 'true' }}
        uses: "./.github/workflows/build-image.yaml"
        with:
            image: "seed-data"
            path: "./containers/seed-data"

    # Search vectors container jobs
    build-search-vectors-container:
        runs-on: ubuntu-latest
        needs: [filter-changes]
        if: ${{ needs.filter-changes.outputs.search-vectors-container-changed == 'true' }}
        steps:
            - name: hello-step
              run: echo "search-vectors-container changed!"

    # Wait bucket ready container jobs
    build-wait-bucket-ready-container:
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write
        needs: [filter-changes]
        if: ${{ needs.filter-changes.outputs.wait-bucket-ready-container-changed == 'true' }}
        uses: "./.github/workflows/build-image.yaml"
        with:
            image: "wait-bucket-ready"
            path: "./containers/wait-bucket-ready"

    # Final check
    final-check:
        runs-on: ubuntu-latest
        needs: [filter-changes, build-seed-data-container, build-search-vectors-container, build-wait-bucket-ready-container]  # It depends on all jobs
        if: always()
        steps:
        - name: Check previous job statuses
          run: |
            if [ "${{ needs.filter-changes.result }}" == "failure" ] || \
                [ "${{ needs.build-seed-data-container.result }}" == "failure" ] || \
                [ "${{ needs.build-search-vectors-container.result }}" == "failure" ] || \
                [ "${{ needs.build-wait-bucket-ready-container.result }}" == "failure" ]; then
                echo "One or more jobs have failed."
                exit 1
            else
                echo "All jobs succeeded or were skipped."
            fi